qualitywise7org/qualitywise7.github.io

biographies/index.html, businessplans/index.html, career/index.html, careeroptions/index.html, careeroptions/jobdetails/index.html, careeroptions/profileanalyzer/index.html, careeroptions/profileanalyzer/js/profileanalyzer.js, curriculum/index.html, demo/index.html, index.html, motivation/index.html, myaccount/index.html, myaccount/jobsforyou/index.html, pricing/index.html, pricing/style.css, privacy/index.html, sitemap.xml, socialwork/index.html, website_data/jobs_data.js, website_data/website_masterdata.js
Modify the pricing and curriculum page , and also add link books Donate in footer
=> Pricing,curriculum: improving the pricing and curriculum

sitemap.xml
add curriculum link in sitemap.xml
=> sitemap:add curriculum link in sitemap.xml

test/index.html
Making the new layout of the test page and adding the englisht test in it
=> fixed the test page

jobs_analysis/index.html, jobsdoor360-website/src/main/ejs/main-files/jobs_analysis/index.ejs
Added table for both job profiles and job posts
=> Added table for both job profiles and job posts

index.html, jobsdoor360-website/src/main/ejs/main-files/index.ejs
Error of like and dislike count button fixed
=> Error of like and dislike count button fixed

results/script.js, results/style.css
=> results page data updated

businessplans/index.html, index.html, jobsdoor360-website/package.json, jobsdoor360-website/src/main/ejs/main-files/businessplans/index.ejs, jobsdoor360-website/src/main/ejs/main-files/index.ejs, jobsdoor360-website/src/main/ejs/main-files/myaccount/yourprofile/index.ejs, myaccount/yourprofile/index.html
blog btn is working on businessplan n complete your profile link is added
=> blog btn is working on businessplan n complete your profile link is added

details/index.html, index.html, jobsdoor360-website/src/main/ejs/main-files/details/index.ejs, jobsdoor360-website/src/main/ejs/main-files/index.ejs
UX course added, create profile font changed.
=> UX course added, create profile font changed.

hiring/index.html, hiring/script.js, jobsdoor360-website/src/main/ejs/main-files/hiring/index.ejs
company_name and job_description is added on jdpanel
=> company_name and job_description is added on jdpanel

index.html, jobsdoor360-website/src/main/ejs/main-files/index.ejs, staticfiles/style.css
Complete your profile to get jobs' else 'create your profile to get jobs
=> Complete your profile to get jobs' else 'create your profile to get jobs

jobsdoor360-website/src/main/ejs/main-files/membership/index.ejs, membership/index.html
=> Changes member ship fee

jobsdoor360-website/src/main/ejs/main-files/myaccount/yourprofile/index.ejs, myaccount/yourprofile/index.html, staticfiles/mainfiles/myaccount/yourprofile/script.js, staticfiles/mainfiles/myaccount/yourprofile/style.css
=> Added profile image section

jobsdoor360-website/src/main/ejs/main-files/login/index.ejs, login/index.html, staticfiles/mainfiles/login/script.js
=> Proper errors in login

buyproject/index.html, index.html, jobsdoor360-website/src/main/ejs/main-files/buyproject/index.ejs, jobsdoor360-website/src/main/ejs/main-files/hiring/index.ejs, jobsdoor360-website/src/main/ejs/main-files/index.ejs
created buy project and promotional section
=> created buy project and promotional section

jobsdoor360-website/src/main/ejs/main-files/hiring/candidate/index.ejs
=> candidate page is created

hiring/candidate/index.html
candidate list page is created
=> candidate list page is created

jobsdoor360-website/src/main/ejs/main-files/myaccount/jobsforyou/index.ejs, myaccount/jobsforyou/index.html
little change in the profile analyzer page
=> little change in the profile analyzer page

jobsdoor360-website/src/main/ejs/main-files/index.ejs
=> fixed spelling mistake

index.html, jobsdoor360-website/src/main/ejs/main-files/pricing/index.ejs, jobsdoor360-website/src/main/ejs/main-files/resend_email_verification/index.ejs, pricing/index.html, resend_email_verification/index.html, staticfiles/mainfiles/resend_email_verification/script.js, staticfiles/mainfiles/resend_email_verification/style.css, staticfiles/mainfiles/signup/script.js
Added page to resend verification email
=> Added page to resend verification email

careeroptions/profileanalyzer/index1.html, index.html, jobsdoor360-website/src/main/ejs/main-files/careeroptions/profileanalyzer/index.ejs, jobsdoor360-website/src/main/ejs/main-files/careeroptions/profileanalyzer/index1.ejs, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js, staticfiles/mainfiles/careeroptions/profileanalyzer/style1.css
profile analyzer page got some new changes
=> profile analyzer page got some new changes

careeroptions/profileanalyzer/index.html, jobsdoor360-website/src/main/ejs/main-files/careeroptions/profileanalyzer/index.ejs, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js, staticfiles/mainfiles/myaccount/jobsforyou/srcipt1.js
profile count added on profile analyzer page & location search is fixed on the jobs for u page
=> profile count added on profile analyzer page & location search is fixed on the jobs for u page

jobsdoor360-website/src/main/ejs/main-files/myaccount/jobsforyou/index.ejs, myaccount/jobsforyou/index.html, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js, staticfiles/mainfiles/careeroptions/profileanalyzer/style1.css
in profile analyzer page click_here button dynamically getting urls
=> in profile analyzer page click_here button dynamically getting urls

apply/index.html, careeroptions/profileanalyzer/index1.html, myaccount/cv_upload/index.html, myaccount/jdpanel/index.html, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js
URL fixed in profile analyzer page
=> URL fixed in profile analyzer page

apply/cv_upload/index.html, jobsdoor360-website/src/main/ejs/main-files/apply/cv_upload/index.ejs, staticfiles/mainfiles/apply/cv_upload/script.js
Added college field in apply/cv field
=>  Added college field in apply/cv field.

jobsdoor360-website/src/main/ejs/main-files/myaccount/yourprofile/index.ejs, myaccount/yourprofile/index.html, staticfiles/mainfiles/myaccount/yourprofile/script.js
chnages in email text box college field and experience
=> changes in profile

about/index.html, careeroptions/profileanalyzer/index.html, index.html, jobsdoor360-website/src/main/ejs/main-files/about/index.ejs, jobsdoor360-website/src/main/ejs/main-files/careeroptions/profileanalyzer/index.ejs, jobsdoor360-website/src/main/ejs/main-files/index.ejs, staticfiles/mainfiles/about/style.css, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js, staticfiles/mainfiles/login/script.js, staticfiles/mainfiles/style.css
1.after login - redirect to myaccount page
2.job name and link on profile analyzer. remove share button
3.on profile analyzer page - add link of job analysis
4.demo class available and apply button - comment code
5.about us design fix
6.home page search button design improvement
=> made some changes in website

jobsdoor360-website/src/main/ejs/main-files/myaccount/yourprofile/index.ejs, jobsdoor360-website/src/main/ejs/main-files/test/index.ejs, jobsdoor360-website/src/main/ejs/main-files/test/quiz/index.ejs, myaccount/yourprofile/index.html, staticfiles/mainfiles/myaccount/yourprofile/script.js, staticfiles/mainfiles/test/quiz/script.js, staticfiles/mainfiles/test/quiz/style.css, staticfiles/mainfiles/test/script.js, staticfiles/mainfiles/test/style.css, test/index.html, test/quiz/index.html
Added profile completion bars and calculation logic to your profile page also Added guideline popup and removed that from test page.
=> Added profile completion bars and Added guideline popup on quiz page.

careeroptions/profileanalyzer/index.html, jobsdoor360-website/ejs_compiler.js, jobsdoor360-website/src/main/ejs/main-files/careeroptions/profileanalyzer/index.ejs, jobsdoor360-website/src/main/ejs/main-files/myaccount/yourprofile/index.ejs, staticfiles/mainfiles/careeroptions/profileanalyzer/script1.js, website_data/website_masterdata.js
Also fixed a little css in skill section of my profile page.
=> Added Salary Range in Profile Analyzer and Successfully added content using ejs in profile analyzer page for SEO.

jobsdoor360-website/src/main/ejs/main-files/myaccount/jobsforyou/index.ejs, myaccount/jobsforyou/index.html
=> Company filter added

staticfiles/mainfiles/myaccount/jobsforyou/srcipt1.js
improving working of  filters creating array for all  desired inputs
=> improving working of  filters

jobsdoor360-website/src/main/ejs/main-files/myaccount/jobsforyou/index.ejs, myaccount/jobsforyou/index.html, staticfiles/db/dbconfig.js, staticfiles/mainfiles/myaccount/jobsforyou/srcipt1.js, staticfiles/mainfiles/myaccount/jobsforyou/style.css
Added clear All button and changed position of search button and added functionality of clear all button
=> Added clear All button and changed position of search button

jobsdoor360-website/src/main/ejs/main-files/myaccount/jobsforyou/index.ejs, myaccount/jobsforyou/index.html, staticfiles/mainfiles/myaccount/jobsforyou/srcipt1.js
added a qualification input checkbox that fetch qualifications from user profile and put it in qualification input field
=> added a qualification input checkbox

staticfiles/mainfiles/myaccount/jobsforyou/srcipt1.js
adding a google analytics for search events
=> adding a google analytics for search events

staticfiles/db/dbconfig.js, staticfiles/mainfiles/forgotpassword/script.js
solving problem of forgot password
=> solving problem of forgot password

.vscode/settings.json, staticfiles/mainfiles/myaccount/style.css, staticfiles/mainfiles/myaccount/yourprofile/style.css
=> mobile veiw update

biographies/osho-rajneesh/index.html, jobsdoor360-website/src/main/ejs/main-files/biographies/osho-rajneesh/index.ejs
Created page for Osho Rajneesh biography
=> osho-rajneesh-biography

biographies/falguni-nayar/index.html, biographies/index.html, biographies/melanie-perkins(canva-founder)/index.html, biographies/phil-knight(nike-founder)/index.html, biographies/reed-hastings(netflix-founder)/index.html, biographies/upasana-taku(MobiKwik-founder)/index.html, biographies/vijay-shekhar-sharma(paytm-founder)/index.html, biographies/zoho-sridhar-vembu/index.html, jobsdoor360-website/src/main/ejs/main-files/biographies/falguni-nayar/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/melanie-perkins(canva-founder)/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/phil-knight(nike-founder)/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/reed-hastings(netflix-founder)/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/upasana-taku(MobiKwik-founder)/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/vijay-shekhar-sharma(paytm-founder)/index.ejs, jobsdoor360-website/src/main/ejs/main-files/biographies/zoho-sridhar-vembu/index.ejs
biography pages added for-
Nayka founder
Paytm founder 
Mobikwik founder 
phil knight Nike ower
canva founder Melani Pekins
Netflix owner Reed Hastings
=> biography-pages-added
